---
title: ""
author: Matthew Bain
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: false
    includes:
      in_header: !expr fs::path_package("autocv", "extdata/latex","custom_resume.tex")
# TODO: archive?
# Turn off header and footer (\customshowheaders{true/false})
# header-includes:
#   - |
#     \newif\ifcustomshowheaders
#     \customshowheadersfalse
fontsize: 11pt
geometry: margin=0.55in, bottom=0.5in, headsep=0.15in, footskip=0.15in
params:
  # resume_data_filename: "resume_data.xlsx"
  target: "app"
  app_id: "latest"
  app_period: "latest"
  use_abridged: FALSE
  sort_appended: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(autocv)
library(glue)
library(dplyr)

target        <- params$target
app_id        <- params$app_id
app_period    <- params$app_period
use_abridged  <- params$use_abridged
sort_appended <- params$sort_appended

# Load data and preprocess
skill_data <- autocv::load_application_data(
  target = target,
  filename = "resume_data.xlsx",
  sheet = "skills",
  # skip = 2
  app_id = app_id,
  app_period = app_period
) %>% autocv::sort_skills(., target = target, use_abridged = use_abridged)

position_data <- autocv::load_application_data(
  target = target,
  filename = "resume_data.xlsx",
  sheet = "entries",
  # skip = 1
  app_id = app_id,
  app_period = app_period
) %>% autocv::preprocess_entries(
  .,
  style = "latex",
  bullet_style = "-",
  use_abridged = use_abridged,
  sort_appended = sort_appended,
  skill_set_sorted = skill_data
)

contact_data <- autocv::load_application_data(
  target = target,
  filename = "cover_data.xlsx",
  sheet = "contact_info",
  app_id = app_id,
  app_period = app_period
) %>% autocv::preprocess_contacts(., style = "latex")

text_data <- autocv::load_application_data(
  target = target,
  filename = "cover_data.xlsx",
  sheet = "text_blocks",
  app_id = app_id,
  app_period = app_period
) %>% autocv::preprocess_text(use_abridged = use_abridged)

```

```{r extract, include=FALSE}

name <- contact_data$address_text[contact_data$loc == "name"]
role <- text_data$text[text_data$loc == "title"]
bio <- text_data$text[text_data$loc == "bio"]
suffix <- contact_data$address_text[contact_data$loc == "title"]

contacts_text <- autocv::print_contact_info(
  contact_data, 
  section = "info", 
  sep = " | "
)
links_text <- autocv::print_contact_info(
  contact_data, 
  section = "links", 
  sep = " | "
)

skills_list <- autocv::build_skill_list(
  skill_data, 
  sep = " • ",
  separate_competencies = TRUE,
  competencies_header = "Other"
)

```

\myname{`r paste0(name, ", ", suffix)`} `r paste(contacts_text)`

<!-- \vspace{-4pt} -->
<!-- ### \myrole{`r paste(role)`} -->

\vspace{-4pt}
`r paste(links_text)`

\mybio{`r paste(bio)`}

## \mysection{Skills} \mysectionrule{}

\vspace{-4pt}
`r paste(skills_list)`

<!-- `r paste(build_skill_table(skill_data))` -->

## \mysection{Selected Professional Experience} \mysectionrule{}

```{r jobs}
autocv::print_latex_section(
  position_data, 
  section_id = "work", 
  short_entries = TRUE, 
  target = target
)
```

## \mysection{Education} \mysectionrule{}

```{r education}
autocv::print_latex_section(
  position_data, 
  section_id = "education", 
  short_entries = TRUE, 
  target = target
)
```

## \mysection{Certifications} \mysectionrule{}

```{r certificates}
autocv::print_latex_section(
  position_data,
  section_id = "certifications",
  short_entries = TRUE,
  target = target
)
```

## \mysection{Selected Projects} \mysectionrule{}

```{r projects}
autocv::print_latex_section(
  position_data,
  section_id = "projects",
  short_entries = TRUE,
  target = target
)
```

\label{LastPage}
